# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        container_name: laravel_atuh_demo
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        working_dir: /home/homepage
        volumes:
            - '.:/home/homepage'
            - taisei_stores:/workspace/node_modules
            - taisei_stores:/workspace/vendor
            - taisei_stores:/workspace/storage/framework
            # - ../:/home/homepage:cached
            # - /home/homepage/storage/framework
            # - /home/homepage/vendor
            # - ./app:/home/homepage/app
            # - ./config:/home/homepage/config
            # - ./database:/home/homepage/database
            # - ./public_html:/home/homepage/public_html
            # - ./resources:/home/homepage/resources
            # - ./routes:/home/homepage/routes
        depends_on:
            - mysql
                # networks:
                #     - sail
                #     - redis
                #     - meilisearch
                #     - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            
            MYSQL_TCP_PORT: '${DB_PORT}'
        expose:
            - '${DB_PORT}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            #  - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            #     networks:
            #         - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sail-redis:/data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "redis-cli", "ping"]
    #         retries: 3
    #         timeout: 5s
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     volumes:
    #         - 'sail-meilisearch:/meili_data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
    #         retries: 3
    #         timeout: 5s
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
        environment:
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_HOST: mysql
        # networks:
        #     - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        # networks:
        #   - sail
        # selenium:
        #     image: 'selenium/standalone-chrome'
        #     volumes:
        #         - '/dev/shm:/dev/shm'
        #     networks:
        #         - sail
        # networks:
        #     sail:
        #         driver: bridge
volumes:
    sail-mysql:
        driver: local
        # sail-redis:
        #     driver: local
        # sail-meilisearch:
        #     driver: local
    taisei_stores:
